import { HttpException, HttpStatus } from '@nestjs/common';
import {
  caughtBody,
  caughtResponse,
  makeFilter,
} from '../support/problem-harness';

/**
 * RFC 9457 §3.1.2 "status":
 *
 *   The "status" member is a JSON number indicating the HTTP status code
 *   generated by the origin server for this occurrence of the problem.
 *   ... Generators MUST use the same status code in the actual HTTP response.
 *
 * The end-to-end version of this invariant (over a real Nest HTTP response) is
 * in tests/rfc9457/integration.spec.ts — that is the authoritative check.
 */
describe('RFC 9457 §3.1.2 — status', () => {
  afterEach(() => jest.clearAllMocks());

  it('MUST be a JSON number', () => {
    const f = makeFilter();
    const body = caughtBody(f, new HttpException('Oops', HttpStatus.NOT_FOUND));

    expect(typeof body.status).toBe('number');
    expect(Number.isInteger(body.status)).toBe(true);
  });

  // Status flows straight through to both the body and the reply — there is no
  // per-code branching here, so a handful of representative and boundary
  // values (rather than a large random sample) is sufficient to establish the
  // invariant.
  it.each([100, 200, 226, 308, 400, 404, 451, 500, 599])(
    'generators MUST use the same status code (%i) in the actual HTTP response',
    (status) => {
      const f = makeFilter();
      const ex = new HttpException('Oops', status);

      const { body, status: replied } = caughtResponse(f, ex);

      expect(body.status).toBe(status);
      expect(replied).toBe(status);
      expect(body.status).toBe(replied);
    },
  );

  it('MUST remain a JSON number after serialization', () => {
    const f = makeFilter();
    const body = caughtBody(f, new HttpException('Oops', HttpStatus.NOT_FOUND));

    const roundTripped = JSON.parse(JSON.stringify(body));
    expect(typeof roundTripped.status).toBe('number');
  });
});
