import type { SchemaObject } from '@nestjs/swagger/dist/interfaces/open-api-spec.interface';

/**
 * OpenAPI 3.0 schema for an RFC 9457 (formerly RFC 7807) Problem Details
 * response body. Mirrors `docs/openapi.md` so the documented schema and the
 * one injected by `@ApiProblemResponse()` stay in sync.
 *
 * Inlined (no `$ref`) so the decorator works without requiring callers to
 * register extra models on `SwaggerModule`.
 */
export const PROBLEM_DETAILS_SCHEMA: SchemaObject = {
  type: 'object',
  description:
    'Problem Details object as defined by RFC 9457 (formerly RFC 7807). ' +
    'Returned with media type `application/problem+json`.',
  required: ['type', 'title', 'status'],
  additionalProperties: true,
  properties: {
    type: {
      type: 'string',
      format: 'uri-reference',
      maxLength: 1024,
      default: 'about:blank',
      description:
        'A URI reference that identifies the problem type. Per RFC 9457 ' +
        'this is a URI-reference (may be relative). Defaults to ' +
        '"about:blank" when not provided.',
      example: 'about:blank',
    },
    title: {
      type: 'string',
      maxLength: 1024,
      description:
        'A short, human-readable summary of the problem type. It should ' +
        'not change from occurrence to occurrence of the problem, except ' +
        'for purposes of localization.',
    },
    status: {
      type: 'integer',
      format: 'int32',
      minimum: 100,
      maximum: 599,
      description:
        'The HTTP status code generated by the origin server for this ' +
        'occurrence of the problem.',
    },
    detail: {
      type: 'string',
      maxLength: 4096,
      description:
        'A human-readable explanation specific to this occurrence of the ' +
        'problem.',
    },
    instance: {
      type: 'string',
      format: 'uri-reference',
      maxLength: 1024,
      description:
        'A URI reference that identifies the specific occurrence of the ' +
        'problem.',
    },
    code: {
      type: 'string',
      maxLength: 50,
      description:
        'Optional API-specific error code (extension member, not part of ' +
        'RFC 9457).',
    },
    'invalid-params': {
      type: 'array',
      maxItems: 1000,
      description:
        'Array of validation errors per the RFC 9457 §3 canonical example. ' +
        'Preferred extension member for validation failures.',
      items: {
        type: 'object',
        required: ['name', 'reason'],
        additionalProperties: true,
        properties: {
          name: {
            type: 'string',
            maxLength: 1024,
            description:
              'Name of the parameter (body property, query/path parameter, or header).',
          },
          reason: {
            type: 'string',
            maxLength: 4096,
            description:
              'Human-readable reason the parameter failed validation.',
          },
        },
      },
    },
    errors: {
      type: 'array',
      maxItems: 1000,
      description:
        'Alternative SmartBear-style array of granular error details. Use ' +
        '`invalid-params` for validation; this member is accepted but not ' +
        'preferred.',
      items: {
        type: 'object',
        required: ['detail'],
        additionalProperties: true,
        properties: {
          detail: { type: 'string', maxLength: 4096 },
          pointer: {
            type: 'string',
            maxLength: 1024,
            description: 'JSON Pointer to a request body property.',
          },
          parameter: {
            type: 'string',
            maxLength: 1024,
            description: 'Query or path parameter name.',
          },
          header: {
            type: 'string',
            maxLength: 1024,
            description: 'Request header name.',
          },
          code: { type: 'string', maxLength: 50 },
        },
      },
    },
  },
};
