
name: Release Node.js Package

on:
  release:
    types: [created]

jobs:
  release-nest-problem-details-filter:
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://www.npmjs.com/package/nest-problem-details-filter
    permissions:
      contents: read
      id-token: write
    defaults:
      run:
        working-directory: libs/nest-problem-details-filter  
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          registry-url: 'https://registry.npmjs.org'

      - run: npm install
      - run: npm run lint
      - run: npm test
      - run: npm publish --provenance --access public